image: maven:3-eclipse-temurin-21

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  GIT_DEPTH: "0"  

stages:
  - sonarqube-check
  - sonarqube-vulnerability-report
  - dependency-check

sonarqube-check:
  stage: sonarqube-check
  script: 
    - mvn clean package -DskipTests 
    - mvn sonar:sonar  
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  tags:
    - runner2-dev-shell 

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=test-gitlab-ci&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  tags:
    - runner2-dev-shell 

dependency-check:
  stage: dependency-check
  script:
    - mvn org.owasp:dependency-check-maven:check
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  tags:
    - runner2-dev-shell 
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json