---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  PRODUCT_SERVICE_URL: "http://product-service.default.svc.cluster.local:8080"
  ORDER_SERVICE_URL: "http://order-service.default.svc.cluster.local:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service.default.svc.cluster.local:8082"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.default.svc.cluster.local:29092"
  IDENTITY_SERVICE_URL: "http://identity-service.default.svc.cluster.local:8087"
